/**
 * src/content/map.ts
 * ------------------
 * The whole of Varath, as one continuous walkable map (RULE 3). Ironvale, the
 * walled city, sits at the CENTRE of the world; the six wilderness regions are
 * spread out in a ring around it and joined to its gates by roads:
 *
 *                      The Spine (north)
 *        Marrow Deeps (NE) ·  IRONVALE  · (the home Knuckle Hills wrap it)
 *        Greyoak (west)   ·   [centre]  ·  Redrun & Sea (east)
 *              Heartmoor (SW)  ·  Ashfen Flats (south)
 *
 * Each wilderness region keeps the exact internal layout it always had — it is
 * generated by the same tile rule, just translated to its new home (so every
 * resource/monster keeps its relative place). Ironvale is hand-built at the
 * centre with a market street, a civic yard and four gates. Roads are carved
 * last so the centre always connects out to every region.
 */

import type { TileType, WorldMap } from "../core/types.ts";

const WIDTH = 112;
/** The overworld is rows 0–107; below it are sealed bands of boss arenas and,
 *  below those, the private interiors of player homes (both reached only by a
 *  teleport, so they never touch the walkable overworld). */
export const OVERWORLD_HEIGHT = 108;
const ARENA_BAND = 16;
const INTERIOR_BAND = 14;
const HEIGHT = OVERWORLD_HEIGHT + ARENA_BAND + INTERIOR_BAND;

export { WIDTH as MAP_WIDTH };

/**
 * The four boss arenas, isolated in the hidden band below the overworld (you can
 * only reach them by a portal that teleports you in). Each is a walled room with
 * a floor tile of its own. x is the left column; the room is ARENA_W × ARENA_H.
 */
export const ARENA_W = 13;
export const ARENA_H = 12;
export const ARENA_TOP = OVERWORLD_HEIGHT + 2;
export const ARENAS: { dungeon: string; x: number; floor: TileType }[] = [
  { dungeon: "hollow_barrows", x: 2, floor: "dirt" },
  { dungeon: "bog_barrow", x: 18, floor: "bog" },
  { dungeon: "spine_vault", x: 34, floor: "stone" },
  { dungeon: "marrow_vault", x: 50, floor: "cave" },
];

/**
 * Player-home interiors: each home is a small, lived-in HOUSE in the hidden band
 * below the arenas — four rooms sharing walls, joined by doorways (OSRS/Skyrim
 * style). You enter the LIVING room; the KITCHEN and BEDROOM open off it through
 * doorways; the WORKSHOP is a wing you add on (its doorway is sealed until you
 * build the extension). `homeLayout(ox)` is the single source of truth for the
 * floorplan — both decode() (carving) and spawns.ts (objects) read it.
 */
export const INTERIOR_TOP = OVERWORLD_HEIGHT + ARENA_BAND; // first row of the band
const HOUSE_W = 15; // each house footprint is 15 wide × 11 tall

interface V { x: number; y: number }
export interface HomeLayout {
  rooms: { name: string; x0: number; y0: number; x1: number; y1: number }[];
  /** Plank openings punched through the walls (doorways + the entrance). */
  doorways: V[];
  /** Where you land entering (just inside the entrance, in the living room). */
  entry: V;
  /** The interior exit-door tile (the entrance doorway). */
  exitDoor: V;
  /** The sealed workshop-wing doorway (a room_seal stands here until built). */
  sealDoor: V;
  /** Every furniture footing, with its category and room. */
  footings: { category: string; room: string; x: number; y: number }[];
}

/** The floorplan for the home whose interior origin is column `ox`. */
export function homeLayout(ox: number): HomeLayout {
  const oy = INTERIOR_TOP;
  return {
    rooms: [
      { name: "bedroom", x0: ox, y0: oy, x1: ox + 7, y1: oy + 5 },
      { name: "workshop", x0: ox + 7, y0: oy, x1: ox + 14, y1: oy + 5 },
      { name: "kitchen", x0: ox, y0: oy + 5, x1: ox + 7, y1: oy + 10 },
      { name: "living", x0: ox + 7, y0: oy + 5, x1: ox + 14, y1: oy + 10 },
    ],
    doorways: [
      { x: ox + 7, y: oy + 7 },   // living ↔ kitchen
      { x: ox + 3, y: oy + 5 },   // kitchen ↔ bedroom
      { x: ox + 11, y: oy + 5 },  // living ↔ workshop (sealed until built)
      { x: ox + 11, y: oy + 10 }, // entrance (living ↔ lot)
    ],
    entry: { x: ox + 11, y: oy + 9 },
    exitDoor: { x: ox + 11, y: oy + 10 },
    sealDoor: { x: ox + 11, y: oy + 5 },
    footings: [
      { category: "bed", room: "bedroom", x: ox + 2, y: oy + 2 },
      { category: "display", room: "bedroom", x: ox + 5, y: oy + 1 },
      { category: "lighting", room: "bedroom", x: ox + 5, y: oy + 3 },
      { category: "workshop", room: "workshop", x: ox + 9, y: oy + 2 },
      { category: "forge", room: "workshop", x: ox + 12, y: oy + 1 },
      { category: "alchemy", room: "workshop", x: ox + 12, y: oy + 3 },
      { category: "kitchen", room: "kitchen", x: ox + 2, y: oy + 6 },
      { category: "storage", room: "kitchen", x: ox + 5, y: oy + 6 },
      { category: "lighting", room: "kitchen", x: ox + 2, y: oy + 8 },
      { category: "hall", room: "living", x: ox + 13, y: oy + 6 },
      { category: "lighting", room: "living", x: ox + 9, y: oy + 6 },
      { category: "display", room: "living", x: ox + 13, y: oy + 8 },
      { category: "table", room: "living", x: ox + 10, y: oy + 8 },
      { category: "seating", room: "living", x: ox + 8, y: oy + 9 },
    ],
  };
}

/** Each home: its interior origin column + its overworld lot tiles. */
export const HOMES: {
  plot: string; ox: number;
  lot: { marker: V; door: V; exit: V };
}[] = [
  { plot: "home_redmouth", ox: 2, lot: { marker: { x: 81, y: 64 }, door: { x: 84, y: 65 }, exit: { x: 84, y: 66 } } },
  { plot: "home_drover", ox: 20, lot: { marker: { x: 74, y: 73 }, door: { x: 77, y: 74 }, exit: { x: 77, y: 75 } } },
  { plot: "home_fold", ox: 38, lot: { marker: { x: 59, y: 8 }, door: { x: 62, y: 9 }, exit: { x: 62, y: 10 } } },
];
export { HOUSE_W as HOME_WIDTH };

/** A cheap, stable pseudo-noise so terrain is fixed (not random). */
function noise(x: number, y: number): number {
  const n = Math.sin(x * 157.31 + y * 113.77) * 43758.5453;
  return n - Math.floor(n);
}

// --- Region tile rules. Each takes coordinates in the region's ORIGINAL local
// space (the same numbers it always used), so the internal layout is unchanged;
// decode() maps each new-canvas tile back to those local coords. ---

function forestTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the Lodge road
  const fringe = x < 2 || x > 25;
  const inClearing = y >= 24 && y <= 27 && x >= 5 && x <= 22;
  if (inClearing) return "dirt";
  return fringe ? "grass" : "moss";
}

function spineTile(x: number, y: number): TileType {
  const sx = x - 28;
  if ((x === 39 || x === 40) && y >= 9 && y <= 27) return "water"; // Cold Stream
  if (sx <= 3 && y >= 5 && y <= 9) return "stone"; // the pass off the hills
  const peakChance = sx < 6 ? 0.78 : 0.7;
  if (noise(x, y) > peakChance) return "mountain";
  return sx < 6 || y < 5 ? "stone" : "snow";
}

function marrowTile(x: number, y: number): TileType {
  if (noise(x, y) > 0.6) return "cave_wall";
  return "cave";
}

function heartmoorTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the road continues south
  const n = noise(x, y);
  if (n > 0.84) return "water"; // bog pools (impassable)
  if (n < 0.12) return "grass"; // firmer tussocks
  return "bog";
}

function ashfenTile(x: number, y: number): TileType {
  if (noise(x, y) > 0.85) return "stone"; // warm outcrops
  return "ash";
}

function redrunTile(x: number, y: number): TileType {
  if (y >= 51) return "deep"; // the open Eyeless Sea to the south
  const widen = Math.floor((y - 28) / 7);
  const left = 54 - widen;
  const right = 57 + widen;
  if (x >= left && x <= right) return "water"; // the red river, widening
  return noise(x, y) > 0.72 ? "dirt" : "grass"; // banks
}

/**
 * Each wilderness region: its tile rule, the top-left of its ORIGINAL local
 * coordinate box, its size, and where that box now sits on the bigger canvas.
 * `dx/dy` (new origin − old origin) is exported so spawns.ts can shift every
 * object the same way and stay perfectly aligned with the terrain.
 */
export interface RegionPlacement {
  key: string;
  fn: (x: number, y: number) => TileType;
  ogx: number; ogy: number; // original local origin
  w: number; h: number;
  nx: number; ny: number; // new origin on the canvas
}

export const REGIONS: RegionPlacement[] = [
  { key: "spine", fn: spineTile, ogx: 28, ogy: 0, w: 20, h: 34, nx: 38, ny: 2 },
  { key: "marrow", fn: marrowTile, ogx: 48, ogy: 0, w: 16, h: 28, nx: 82, ny: 6 },
  { key: "redrun", fn: redrunTile, ogx: 48, ogy: 28, w: 16, h: 28, nx: 90, ny: 60 },
  { key: "ashfen", fn: ashfenTile, ogx: 28, ogy: 34, w: 20, h: 22, nx: 50, ny: 82 },
  { key: "heartmoor", fn: heartmoorTile, ogx: 0, ogy: 34, w: 28, h: 22, nx: 8, ny: 80 },
  { key: "greyoak", fn: forestTile, ogx: 0, ogy: 18, w: 28, h: 16, nx: 6, ny: 46 },
];

/** Per-region spawn shift (new origin − old origin). Keyed by region. */
export const REGION_OFFSET: Record<string, { dx: number; dy: number }> = Object.fromEntries(
  REGIONS.map((r) => [r.key, { dx: r.nx - r.ogx, dy: r.ny - r.ogy }]),
);

/** The arena band moved down with the taller overworld; spawns shift by this. */
export const ARENA_OFFSET = { dx: 0, dy: ARENA_TOP - 58 };

// --- Ironvale, the central city (hand-built). ---
// A walled rectangle with four gates. West half is the civic yard (bank, forge,
// stations); the east half is the market street, lined with stalls. The home
// Knuckle Hills (grove, outcrop, lake, farmstead) wrap the city outside.
export const CITY = { x0: 44, y0: 38, x1: 79, y1: 67 };
/** Gate centres, in canvas coords — roads meet the city here. */
export const GATES = {
  north: { x: 60, y: CITY.y0 },
  south: { x: 60, y: CITY.y1 },
  west: { x: CITY.x0, y: 52 },
  east: { x: CITY.x1, y: 52 },
};
/** A good, central, walkable spawn tile for the player (the civic yard). */
export const CITY_SPAWN = { x: 55, y: 52 };

/** A roofed building in Ironvale. Its footprint blocks; the renderer roofs it. */
export type RoofStyle = "slate" | "tile" | "thatch" | "tower";
export interface Building {
  x0: number; y0: number; x1: number; y1: number;
  roof: RoofStyle;
  /** Door cell (on the building's front), for the rendered doorway. */
  door?: { x: number; y: number };
}

// The city's buildings, by district. Footprints avoid the gate-streets
// (x59–61 / y51–53) and leave a walkable frontage where the shopkeepers stand.
// Buildings hug the inside of the ramparts, leaving the central yards and the
// gate-streets (x59–61 / y51–53) open for the stalls, stations and crowds.
export const BUILDINGS: Building[] = [
  // --- North wall row ---
  { x0: 45, y0: 39, x1: 49, y1: 41, roof: "slate", door: { x: 47, y: 41 } },  // The Ashforge
  { x0: 51, y0: 39, x1: 55, y1: 41, roof: "tile", door: { x: 53, y: 41 } },   // The Varath Vault
  { x0: 62, y0: 39, x1: 66, y1: 41, roof: "tile", door: { x: 64, y: 41 } },   // Quartermaster's Store
  { x0: 68, y0: 39, x1: 72, y1: 41, roof: "slate", door: { x: 70, y: 41 } },  // The Armoury
  { x0: 75, y0: 39, x1: 78, y1: 42, roof: "tower", door: { x: 76, y: 42 } },  // The Watchtower
  // --- West wall ---
  { x0: 45, y0: 44, x1: 47, y1: 49, roof: "slate", door: { x: 47, y: 49 } },  // The Pale Record
  { x0: 45, y0: 55, x1: 47, y1: 60, roof: "thatch", door: { x: 47, y: 60 } }, // houses
  // --- East wall ---
  { x0: 76, y0: 44, x1: 78, y1: 49, roof: "thatch", door: { x: 76, y: 49 } },
  { x0: 76, y0: 55, x1: 78, y1: 60, roof: "thatch", door: { x: 76, y: 55 } },
  // --- South wall row ---
  { x0: 45, y0: 64, x1: 50, y1: 66, roof: "slate", door: { x: 47, y: 64 } },  // The Craftworks
  { x0: 52, y0: 64, x1: 57, y1: 66, roof: "tile", door: { x: 54, y: 64 } },   // The Mending House
  { x0: 62, y0: 64, x1: 66, y1: 66, roof: "thatch", door: { x: 64, y: 64 } }, // Skritt's Exchange
  { x0: 68, y0: 64, x1: 73, y1: 66, roof: "tile", door: { x: 70, y: 64 } },   // The Wayfarers' Lodge
  { x0: 75, y0: 64, x1: 78, y1: 66, roof: "thatch", door: { x: 76, y: 64 } },

  // === OUTLYING SETTLEMENTS — small hamlets in the open country between =====
  // regions. Each is a cluster of roofed cottages on carved ground (see step 4d
  // in decode), home to a few folk. Ground for player-built housing later.

  // --- Redmouth: a fisherfolk hamlet on the Redrun's east bank ---
  { x0: 83, y0: 58, x1: 85, y1: 59, roof: "thatch", door: { x: 84, y: 59 } },  // a fisher's cottage
  { x0: 87, y0: 58, x1: 89, y1: 59, roof: "thatch", door: { x: 88, y: 59 } },  // the net-loft
  { x0: 83, y0: 61, x1: 85, y1: 62, roof: "thatch", door: { x: 84, y: 61 } },  // the smokehouse
  // --- The Drover's Rest: a waystation on the south road to the Ashfen ---
  { x0: 65, y0: 73, x1: 68, y1: 74, roof: "tile", door: { x: 66, y: 74 } },    // the longhouse inn
  { x0: 70, y0: 73, x1: 72, y1: 74, roof: "thatch", door: { x: 71, y: 74 } },  // a drover's cottage
  { x0: 65, y0: 77, x1: 67, y1: 78, roof: "thatch", door: { x: 66, y: 77 } },  // the byre
  // --- The Fold: an upland shepherds' croft in the Knuckle Hills, north ---
  { x0: 60, y0: 14, x1: 62, y1: 15, roof: "thatch", door: { x: 61, y: 15 } },  // the croft house
  { x0: 64, y0: 14, x1: 66, y1: 15, roof: "thatch", door: { x: 64, y: 15 } },  // the wool-shed
  { x0: 60, y0: 17, x1: 62, y1: 18, roof: "thatch", door: { x: 61, y: 17 } },  // the lambing shed
];

/** Roof style at a tile (so the renderer knows which walls are buildings). */
const roofCells = new Map<string, RoofStyle>();
const doorCells = new Set<string>();
for (const b of BUILDINGS) {
  for (let y = b.y0; y <= b.y1; y++) for (let x = b.x0; x <= b.x1; x++) roofCells.set(`${x},${y}`, b.roof);
  if (b.door) doorCells.add(`${b.door.x},${b.door.y}`);
}
export function cityRoof(x: number, y: number): RoofStyle | undefined { return roofCells.get(`${x},${y}`); }
export function cityDoor(x: number, y: number): boolean { return doorCells.has(`${x},${y}`); }

function decode(): WorldMap {
  const tiles: TileType[] = new Array(WIDTH * HEIGHT).fill("grass");
  const set = (x: number, y: number, t: TileType) => {
    if (x >= 0 && y >= 0 && x < WIDTH && y < HEIGHT) tiles[y * WIDTH + x] = t;
  };
  const carve = (x0: number, y0: number, x1: number, y1: number, t: TileType) => {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) set(x, y, t);
  };

  // 1) The arena band starts as solid wall; rooms are carved later.
  for (let y = OVERWORLD_HEIGHT; y < HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) set(x, y, "wall");
  }

  // 2) Paint each wilderness region at its new home (same internal layout).
  for (const r of REGIONS) {
    for (let cy = r.ny; cy < r.ny + r.h; cy++) {
      for (let cx = r.nx; cx < r.nx + r.w; cx++) {
        const ox = cx - r.nx + r.ogx;
        const oy = cy - r.ny + r.ogy;
        set(cx, cy, r.fn(ox, oy));
      }
    }
  }

  // 3) The home Knuckle Hills wrap the city: a dirt grove + rock outcrop to the
  //    north, a lake to the south-west, open hill grass all around.
  carve(CITY.x0 - 6, CITY.y0 - 14, CITY.x1 + 6, CITY.y0 - 1, "grass"); // hill apron north
  carve(50, 24, 70, 33, "dirt");   // the dirt grove (Forestry)
  carve(82, 28, 92, 38, "stone");  // the knucklestone outcrop (Mining), NE
  carve(34, 70, 43, 82, "water");  // the lake on the city's south-west flank
  carve(CITY.x1 + 1, CITY.y0, CITY.x1 + 7, CITY.y1, "grass"); // east apron to the river road

  // 4) Build Ironvale at the centre.
  //    Plaza floor: stone in the civic (west) half, dirt in the market (east).
  carve(CITY.x0, CITY.y0, CITY.x1, CITY.y1, "stone");
  carve(63, CITY.y0 + 1, CITY.x1 - 1, CITY.y1 - 1, "dirt"); // market ground (east)
  //    Wall ring.
  for (let x = CITY.x0; x <= CITY.x1; x++) { set(x, CITY.y0, "wall"); set(x, CITY.y1, "wall"); }
  for (let y = CITY.y0; y <= CITY.y1; y++) { set(CITY.x0, y, "wall"); set(CITY.x1, y, "wall"); }
  //    Main streets (a cross joining the four gates).
  carve(59, CITY.y0, 61, CITY.y1, "path"); // N–S high street
  carve(CITY.x0, 51, CITY.x1, 53, "path"); // E–W high street
  //    Four gates (open the wall ring where the roads meet it).
  carve(GATES.north.x - 1, CITY.y0, GATES.north.x + 1, CITY.y0, "path");
  carve(GATES.south.x - 1, CITY.y1, GATES.south.x + 1, CITY.y1, "path");
  carve(CITY.x0, GATES.west.y - 1, CITY.x0, GATES.west.y + 1, "path");
  carve(CITY.x1, GATES.east.y - 1, CITY.x1, GATES.east.y + 1, "path");
  //    Outlying hamlets get a packed-dirt yard carved first, so the cottages
  //    that follow sit on cleared ground rather than open field (step 4d names
  //    them). Done before the BUILDINGS loop so the footprints stamp over it.
  carve(81, 57, 90, 63, "dirt");  // Redmouth, on the Redrun's east bank
  carve(63, 72, 73, 79, "dirt");  // The Drover's Rest, on the south road
  carve(58, 13, 67, 19, "dirt");  // The Fold, in the upland Knuckle Hills
  //    A vacant homestead lot beside each hamlet — cleared ground a player can
  //    claim and build a home on (the build hotspots sit in these).
  carve(81, 64, 86, 67, "dirt");  // Redmouth homestead lot, south of the bank
  carve(74, 73, 79, 76, "dirt");  // Drover's Rest homestead lot, east of the yard
  carve(59, 8, 64, 11, "dirt");   // The Fold homestead lot, north of the croft
  //    The buildings: each footprint becomes blocking masonry (the renderer
  //    lays a roof over it). The streets and frontages stay clear between them.
  for (const b of BUILDINGS) carve(b.x0, b.y0, b.x1, b.y1, "wall");
  //    A flagged town square around the crossroads, for the fountain + crowds.
  carve(58, 50, 62, 54, "stone");

  // 4b) Countryside features — the bible's named landmarks get real ground, so
  //     the open country between regions reads as places, not blank field.
  // -- The open Knuckle Hills, north-west of the city --
  carve(8, 6, 14, 12, "dirt");     // Rook's Watch — a high firepit knoll
  carve(18, 8, 26, 16, "stone");   // The Knuckle — the bald stone fist
  carve(14, 18, 22, 24, "dirt");   // an ashwood grove
  carve(28, 29, 33, 34, "water");  // a hill tarn (a head-stream pool)
  carve(5, 30, 11, 36, "stone");   // The Coldvein Scar — a played-out cutting
  // -- The river approach & east banks --
  carve(80, 56, 90, 63, "dirt");   // Redrun banks below the east road
  // -- The moor's edge, south of the city --
  carve(40, 73, 49, 82, "bog");    // where the hill country gives out to moor
  // -- The charburner's country, between wood and moor --
  carve(2, 64, 8, 70, "dirt");     // The Charburner's Clearing
  // -- The warm ground spreading south-east (Ashfen apron) --
  carve(72, 86, 86, 101, "ash");   // warm flats reaching toward the river mouth

  // 4c) Heath: give the remaining open grass a rolling, mixed texture instead of
  //     a flat green sheet (all walkable — grass / dirt / moss hill country).
  for (let y = 0; y < OVERWORLD_HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) {
      if (tiles[y * WIDTH + x] !== "grass") continue;
      const n = noise(x, y);
      if (n > 0.86) set(x, y, "moss");
      else if (n > 0.66) set(x, y, "dirt");
      // else: stays grass
    }
  }

  // 5) Roads from the gates out to each region (kept 3 wide and walkable).
  //    North gate → the Spine pass (its walkable stone pass is at its west edge).
  carve(59, 34, 61, CITY.y0 - 1, "path");          // up through the grove
  carve(44, 34, 61, 36, "path");                    // west along the foot of the Spine
  carve(44, 13, 46, 36, "stone");                   // up into the Spine pass
  //    West gate → Greyoak Wood (just west).
  carve(34, 51, CITY.x0 - 1, 53, "path");
  //    South gate → Ashfen Flats (south) via a moor road.
  carve(59, CITY.y1 + 1, 61, 82, "path");
  //    South-west spur → Heartmoor.
  carve(36, 68, 61, 70, "path");                    // along the lake's north shore
  carve(34, 70, 36, 80, "path");                    // down the lake's west side to the moor
  //    East gate → the Redrun & the river road.
  carve(CITY.x1 + 1, 51, 96, 53, "path");           // east apron
  carve(94, 53, 96, 62, "dirt");                    // down to the riverbank
  //    North-east spur → the Marrow Deeps cave mouth.
  carve(86, 34, 88, 51, "stone");                   // up the outcrop
  carve(86, 34, 90, 36, "cave");                    // into the cave mouth

  // 5b) Short lanes joining the outlying hamlets to the road network.
  carve(84, 54, 85, 57, "path");                    // Redmouth lane up to the east road
  carve(61, 75, 64, 76, "path");                    // The Drover's Rest, off the south road
  carve(58, 19, 60, 24, "path");                    // The Fold, down to the grove

  // 6) Carve the four sealed boss arenas in the band below the overworld.
  for (const a of ARENAS) {
    for (let y = ARENA_TOP; y < ARENA_TOP + ARENA_H; y++) {
      for (let x = a.x; x < a.x + ARENA_W; x++) {
        const edge = x === a.x || x === a.x + ARENA_W - 1 || y === ARENA_TOP || y === ARENA_TOP + ARENA_H - 1;
        set(x, y, edge ? "wall" : a.floor);
      }
    }
  }

  // 7) Carve each player-home interior in the band below the arenas: a four-room
  //    house (walls shared) with plank floors, then punch the doorways through.
  for (const h of HOMES) {
    const plan = homeLayout(h.ox);
    for (const rm of plan.rooms) {
      for (let y = rm.y0; y <= rm.y1; y++) {
        for (let x = rm.x0; x <= rm.x1; x++) {
          const edge = x === rm.x0 || x === rm.x1 || y === rm.y0 || y === rm.y1;
          set(x, y, edge ? "wall" : "plank");
        }
      }
    }
    for (const d of plan.doorways) set(d.x, d.y, "plank"); // openings (incl. the sealed wing doorway)
  }

  return { name: "Varath", width: WIDTH, height: HEIGHT, tiles };
}

export const map: WorldMap = decode();

/** Convenience: read the tile type at a coordinate (grass if out of bounds). */
export function tileAt(m: WorldMap, x: number, y: number): TileType {
  if (x < 0 || y < 0 || x >= m.width || y >= m.height) return "grass";
  return m.tiles[y * m.width + x]!;
}
