/**
 * src/content/map.ts
 * ------------------
 * The whole of Varath, as one continuous walkable map (RULE 3). Ironvale, the
 * walled city, sits at the CENTRE of the world; the six wilderness regions are
 * spread out in a ring around it and joined to its gates by roads:
 *
 *                      The Spine (north)
 *        Marrow Deeps (NE) ·  IRONVALE  · (the home Knuckle Hills wrap it)
 *        Greyoak (west)   ·   [centre]  ·  Redrun & Sea (east)
 *              Heartmoor (SW)  ·  Ashfen Flats (south)
 *
 * Each wilderness region keeps the exact internal layout it always had — it is
 * generated by the same tile rule, just translated to its new home (so every
 * resource/monster keeps its relative place). Ironvale is hand-built at the
 * centre with a market street, a civic yard and four gates. Roads are carved
 * last so the centre always connects out to every region.
 */

import type { TileType, WorldMap } from "../core/types.ts";

const WIDTH = 112;
/** The overworld is rows 0–107; below it is a sealed band of boss arenas. */
export const OVERWORLD_HEIGHT = 108;
const ARENA_BAND = 16;
const HEIGHT = OVERWORLD_HEIGHT + ARENA_BAND;

export { WIDTH as MAP_WIDTH };

/**
 * The four boss arenas, isolated in the hidden band below the overworld (you can
 * only reach them by a portal that teleports you in). Each is a walled room with
 * a floor tile of its own. x is the left column; the room is ARENA_W × ARENA_H.
 */
export const ARENA_W = 13;
export const ARENA_H = 12;
export const ARENA_TOP = OVERWORLD_HEIGHT + 2;
export const ARENAS: { dungeon: string; x: number; floor: TileType }[] = [
  { dungeon: "hollow_barrows", x: 2, floor: "dirt" },
  { dungeon: "bog_barrow", x: 18, floor: "bog" },
  { dungeon: "spine_vault", x: 34, floor: "stone" },
  { dungeon: "marrow_vault", x: 50, floor: "cave" },
];

/** A cheap, stable pseudo-noise so terrain is fixed (not random). */
function noise(x: number, y: number): number {
  const n = Math.sin(x * 157.31 + y * 113.77) * 43758.5453;
  return n - Math.floor(n);
}

// --- Region tile rules. Each takes coordinates in the region's ORIGINAL local
// space (the same numbers it always used), so the internal layout is unchanged;
// decode() maps each new-canvas tile back to those local coords. ---

function forestTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the Lodge road
  const fringe = x < 2 || x > 25;
  const inClearing = y >= 24 && y <= 27 && x >= 5 && x <= 22;
  if (inClearing) return "dirt";
  return fringe ? "grass" : "moss";
}

function spineTile(x: number, y: number): TileType {
  const sx = x - 28;
  if ((x === 39 || x === 40) && y >= 9 && y <= 27) return "water"; // Cold Stream
  if (sx <= 3 && y >= 5 && y <= 9) return "stone"; // the pass off the hills
  const peakChance = sx < 6 ? 0.78 : 0.7;
  if (noise(x, y) > peakChance) return "mountain";
  return sx < 6 || y < 5 ? "stone" : "snow";
}

function marrowTile(x: number, y: number): TileType {
  if (noise(x, y) > 0.6) return "cave_wall";
  return "cave";
}

function heartmoorTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the road continues south
  const n = noise(x, y);
  if (n > 0.84) return "water"; // bog pools (impassable)
  if (n < 0.12) return "grass"; // firmer tussocks
  return "bog";
}

function ashfenTile(x: number, y: number): TileType {
  if (noise(x, y) > 0.85) return "stone"; // warm outcrops
  return "ash";
}

function redrunTile(x: number, y: number): TileType {
  if (y >= 51) return "deep"; // the open Eyeless Sea to the south
  const widen = Math.floor((y - 28) / 7);
  const left = 54 - widen;
  const right = 57 + widen;
  if (x >= left && x <= right) return "water"; // the red river, widening
  return noise(x, y) > 0.72 ? "dirt" : "grass"; // banks
}

/**
 * Each wilderness region: its tile rule, the top-left of its ORIGINAL local
 * coordinate box, its size, and where that box now sits on the bigger canvas.
 * `dx/dy` (new origin − old origin) is exported so spawns.ts can shift every
 * object the same way and stay perfectly aligned with the terrain.
 */
export interface RegionPlacement {
  key: string;
  fn: (x: number, y: number) => TileType;
  ogx: number; ogy: number; // original local origin
  w: number; h: number;
  nx: number; ny: number; // new origin on the canvas
}

export const REGIONS: RegionPlacement[] = [
  { key: "spine", fn: spineTile, ogx: 28, ogy: 0, w: 20, h: 34, nx: 38, ny: 2 },
  { key: "marrow", fn: marrowTile, ogx: 48, ogy: 0, w: 16, h: 28, nx: 82, ny: 6 },
  { key: "redrun", fn: redrunTile, ogx: 48, ogy: 28, w: 16, h: 28, nx: 90, ny: 60 },
  { key: "ashfen", fn: ashfenTile, ogx: 28, ogy: 34, w: 20, h: 22, nx: 50, ny: 82 },
  { key: "heartmoor", fn: heartmoorTile, ogx: 0, ogy: 34, w: 28, h: 22, nx: 8, ny: 80 },
  { key: "greyoak", fn: forestTile, ogx: 0, ogy: 18, w: 28, h: 16, nx: 6, ny: 46 },
];

/** Per-region spawn shift (new origin − old origin). Keyed by region. */
export const REGION_OFFSET: Record<string, { dx: number; dy: number }> = Object.fromEntries(
  REGIONS.map((r) => [r.key, { dx: r.nx - r.ogx, dy: r.ny - r.ogy }]),
);

/** The arena band moved down with the taller overworld; spawns shift by this. */
export const ARENA_OFFSET = { dx: 0, dy: ARENA_TOP - 58 };

// --- Ironvale, the central city (hand-built). ---
// A walled rectangle with four gates. West half is the civic yard (bank, forge,
// stations); the east half is the market street, lined with stalls. The home
// Knuckle Hills (grove, outcrop, lake, farmstead) wrap the city outside.
export const CITY = { x0: 44, y0: 38, x1: 79, y1: 67 };
/** Gate centres, in canvas coords — roads meet the city here. */
export const GATES = {
  north: { x: 60, y: CITY.y0 },
  south: { x: 60, y: CITY.y1 },
  west: { x: CITY.x0, y: 52 },
  east: { x: CITY.x1, y: 52 },
};
/** A good, central, walkable spawn tile for the player (the civic yard). */
export const CITY_SPAWN = { x: 54, y: 52 };

function decode(): WorldMap {
  const tiles: TileType[] = new Array(WIDTH * HEIGHT).fill("grass");
  const set = (x: number, y: number, t: TileType) => {
    if (x >= 0 && y >= 0 && x < WIDTH && y < HEIGHT) tiles[y * WIDTH + x] = t;
  };
  const carve = (x0: number, y0: number, x1: number, y1: number, t: TileType) => {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) set(x, y, t);
  };

  // 1) The arena band starts as solid wall; rooms are carved later.
  for (let y = OVERWORLD_HEIGHT; y < HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) set(x, y, "wall");
  }

  // 2) Paint each wilderness region at its new home (same internal layout).
  for (const r of REGIONS) {
    for (let cy = r.ny; cy < r.ny + r.h; cy++) {
      for (let cx = r.nx; cx < r.nx + r.w; cx++) {
        const ox = cx - r.nx + r.ogx;
        const oy = cy - r.ny + r.ogy;
        set(cx, cy, r.fn(ox, oy));
      }
    }
  }

  // 3) The home Knuckle Hills wrap the city: a dirt grove + rock outcrop to the
  //    north, a lake to the south-west, open hill grass all around.
  carve(CITY.x0 - 6, CITY.y0 - 14, CITY.x1 + 6, CITY.y0 - 1, "grass"); // hill apron north
  carve(50, 24, 70, 33, "dirt");   // the dirt grove (Forestry)
  carve(82, 28, 92, 38, "stone");  // the knucklestone outcrop (Mining), NE
  carve(34, 70, 43, 82, "water");  // the lake on the city's south-west flank
  carve(CITY.x1 + 1, CITY.y0, CITY.x1 + 7, CITY.y1, "grass"); // east apron to the river road

  // 4) Build Ironvale at the centre.
  //    Plaza floor: stone in the civic (west) half, dirt in the market (east).
  carve(CITY.x0, CITY.y0, CITY.x1, CITY.y1, "stone");
  carve(63, CITY.y0 + 1, CITY.x1 - 1, CITY.y1 - 1, "dirt"); // market ground (east)
  //    Wall ring.
  for (let x = CITY.x0; x <= CITY.x1; x++) { set(x, CITY.y0, "wall"); set(x, CITY.y1, "wall"); }
  for (let y = CITY.y0; y <= CITY.y1; y++) { set(CITY.x0, y, "wall"); set(CITY.x1, y, "wall"); }
  //    Main streets (a cross joining the four gates).
  carve(59, CITY.y0, 61, CITY.y1, "path"); // N–S high street
  carve(CITY.x0, 51, CITY.x1, 53, "path"); // E–W high street
  //    The market lane: a path up the east half, with stall plots either side.
  carve(70, CITY.y0 + 2, 70, CITY.y1 - 2, "path");
  //    Four gates (open the wall ring where the roads meet it).
  carve(GATES.north.x - 1, CITY.y0, GATES.north.x + 1, CITY.y0, "path");
  carve(GATES.south.x - 1, CITY.y1, GATES.south.x + 1, CITY.y1, "path");
  carve(CITY.x0, GATES.west.y - 1, CITY.x0, GATES.west.y + 1, "path");
  carve(CITY.x1, GATES.east.y - 1, CITY.x1, GATES.east.y + 1, "path");

  // 5) Roads from the gates out to each region (kept 3 wide and walkable).
  //    North gate → the Spine pass (its walkable stone pass is at its west edge).
  carve(59, 34, 61, CITY.y0 - 1, "path");          // up through the grove
  carve(44, 34, 61, 36, "path");                    // west along the foot of the Spine
  carve(44, 13, 46, 36, "stone");                   // up into the Spine pass
  //    West gate → Greyoak Wood (just west).
  carve(34, 51, CITY.x0 - 1, 53, "path");
  //    South gate → Ashfen Flats (south) via a moor road.
  carve(59, CITY.y1 + 1, 61, 82, "path");
  //    South-west spur → Heartmoor.
  carve(36, 68, 61, 70, "path");                    // along the lake's north shore
  carve(34, 70, 36, 80, "path");                    // down the lake's west side to the moor
  //    East gate → the Redrun & the river road.
  carve(CITY.x1 + 1, 51, 96, 53, "path");           // east apron
  carve(94, 53, 96, 62, "dirt");                    // down to the riverbank
  //    North-east spur → the Marrow Deeps cave mouth.
  carve(86, 34, 88, 51, "stone");                   // up the outcrop
  carve(86, 34, 90, 36, "cave");                    // into the cave mouth

  // 6) Carve the four sealed boss arenas in the band below the overworld.
  for (const a of ARENAS) {
    for (let y = ARENA_TOP; y < ARENA_TOP + ARENA_H; y++) {
      for (let x = a.x; x < a.x + ARENA_W; x++) {
        const edge = x === a.x || x === a.x + ARENA_W - 1 || y === ARENA_TOP || y === ARENA_TOP + ARENA_H - 1;
        set(x, y, edge ? "wall" : a.floor);
      }
    }
  }

  return { name: "Varath", width: WIDTH, height: HEIGHT, tiles };
}

export const map: WorldMap = decode();

/** Convenience: read the tile type at a coordinate (grass if out of bounds). */
export function tileAt(m: WorldMap, x: number, y: number): TileType {
  if (x < 0 || y < 0 || x >= m.width || y >= m.height) return "grass";
  return m.tiles[y * m.width + x]!;
}
