/**
 * src/content/map.ts
 * ------------------
 * The whole of Varath, as one continuous walkable map (RULE 3). Ironvale, the
 * walled city, sits at the CENTRE of a wide world; the six wilderness regions
 * are spread far out in a ring around it, joined to its gates by long roads:
 *
 *                      The Spine (north)
 *        Marrow Deeps (NE) ·  IRONVALE  · (the home Knuckle Hills wrap it)
 *        Greyoak (west)   ·   [centre]  ·  Redrun & Sea (east)
 *              Heartmoor (SW)  ·  Ashfen Flats (south)
 *
 * Each wilderness region keeps the exact internal layout it always had — it is
 * generated by the same tile rule, just translated to its new home (so every
 * resource/monster keeps its relative place). Ironvale and its surrounding
 * Knuckle Hills + hamlets are the "central complex": hand-built, then shifted
 * as a block to the centre of the bigger canvas. Roads are carved last so the
 * centre always connects out to every region across the open country between.
 *
 * Doubling the world (the "spread apart" update): the canvas grew to ~160×164,
 * the central complex moved by CENTRAL_SHIFT, and the regions were pushed much
 * further out. `remap()` is the single transform that re-homes the legacy
 * spawn coordinates onto the new canvas (region spawns by their region's delta;
 * everything else by CENTRAL_SHIFT; the hidden bands drop by BAND_DY).
 */

import type { TileType, WorldMap } from "../core/types.ts";

const WIDTH = 160;
/** The overworld is rows 0–163; below it are sealed bands of boss arenas and,
 *  below those, the private interiors of player homes (both reached only by a
 *  teleport, so they never touch the walkable overworld). */
export const OVERWORLD_HEIGHT = 164;
const ARENA_BAND = 16;
const INTERIOR_BAND = 14;
const HEIGHT = OVERWORLD_HEIGHT + ARENA_BAND + INTERIOR_BAND;

export { WIDTH as MAP_WIDTH };

// --- The "double the map" transform ----------------------------------------
// The whole legacy layout was authored for a 112×108 overworld. The central
// complex (city + Knuckle Hills + hamlets + homes) shifts by CENTRAL_SHIFT;
// each region shifts by its own delta (see LEGACY_REGIONS); the hidden bands
// drop by BAND_DY (the overworld got taller). `remap()` applies this to any
// legacy coordinate so spawns.ts re-homes every object with one call.
const LEGACY_OVERWORLD_HEIGHT = 108;
export const CENTRAL_SHIFT = { dx: 20, dy: 26 };
export const BAND_DY = OVERWORLD_HEIGHT - LEGACY_OVERWORLD_HEIGHT;

/** Where each region used to sit (legacy canvas) + its delta to the new home. */
const LEGACY_REGIONS: Record<string, { nx: number; ny: number; w: number; h: number; dx: number; dy: number }> = {
  spine:     { nx: 38, ny: 2,  w: 20, h: 34, dx: 9,  dy: 3 },
  marrow:    { nx: 82, ny: 6,  w: 16, h: 28, dx: 39, dy: 4 },
  redrun:    { nx: 90, ny: 60, w: 16, h: 28, dx: 44, dy: 41 },
  ashfen:    { nx: 50, ny: 82, w: 20, h: 22, dx: 18, dy: 55 },
  heartmoor: { nx: 8,  ny: 80, w: 28, h: 22, dx: -7, dy: 53 },
  greyoak:   { nx: 6,  ny: 46, w: 28, h: 16, dx: -5, dy: 27 },
};

/** Re-home a legacy overworld/band coordinate onto the new, larger canvas. */
export function remap(x: number, y: number): { x: number; y: number } {
  // The hidden bands (arenas + home interiors) just drop with the taller overworld.
  if (y >= LEGACY_OVERWORLD_HEIGHT) return { x, y: y + BAND_DY };
  // A region's spawns move by that region's delta (keeps them on its terrain).
  for (const r of Object.values(LEGACY_REGIONS)) {
    if (x >= r.nx && x < r.nx + r.w && y >= r.ny && y < r.ny + r.h) {
      return { x: x + r.dx, y: y + r.dy };
    }
  }
  // The central complex (city, hills, hamlets, homes) moves as one block.
  return { x: x + CENTRAL_SHIFT.dx, y: y + CENTRAL_SHIFT.dy };
}

/**
 * The four boss arenas, isolated in the hidden band below the overworld (you can
 * only reach them by a portal that teleports you in). Each is a walled room with
 * a floor tile of its own. x is the left column; the room is ARENA_W × ARENA_H.
 */
export const ARENA_W = 13;
export const ARENA_H = 12;
export const ARENA_TOP = OVERWORLD_HEIGHT + 2;
export const ARENAS: { dungeon: string; x: number; floor: TileType }[] = [
  { dungeon: "hollow_barrows", x: 2, floor: "dirt" },
  { dungeon: "bog_barrow", x: 18, floor: "bog" },
  { dungeon: "spine_vault", x: 34, floor: "stone" },
  { dungeon: "marrow_vault", x: 50, floor: "cave" },
];

/**
 * Player-home interiors: each home is a small, lived-in HOUSE in the hidden band
 * below the arenas — four rooms sharing walls, joined by doorways (OSRS/Skyrim
 * style). You enter the LIVING room; the KITCHEN and BEDROOM open off it through
 * doorways; the WORKSHOP is a wing you add on (its doorway is sealed until you
 * build the extension). `homeLayout(ox)` is the single source of truth for the
 * floorplan — both decode() (carving) and spawns.ts (objects) read it.
 */
export const INTERIOR_TOP = OVERWORLD_HEIGHT + ARENA_BAND; // first row of the band
const HOUSE_W = 15; // each house footprint is 15 wide × 11 tall

interface V { x: number; y: number }
export interface HomeLayout {
  rooms: { name: string; x0: number; y0: number; x1: number; y1: number }[];
  /** Plank openings punched through the walls (doorways + the entrance). */
  doorways: V[];
  /** Where you land entering (just inside the entrance, in the living room). */
  entry: V;
  /** The interior exit-door tile (the entrance doorway). */
  exitDoor: V;
  /** The sealed workshop-wing doorway (a room_seal stands here until built). */
  sealDoor: V;
  /** Every furniture footing, with its category and room. */
  footings: { category: string; room: string; x: number; y: number }[];
}

/** The floorplan for the home whose interior origin is column `ox`. */
export function homeLayout(ox: number): HomeLayout {
  const oy = INTERIOR_TOP;
  return {
    rooms: [
      { name: "bedroom", x0: ox, y0: oy, x1: ox + 7, y1: oy + 5 },
      { name: "workshop", x0: ox + 7, y0: oy, x1: ox + 14, y1: oy + 5 },
      { name: "kitchen", x0: ox, y0: oy + 5, x1: ox + 7, y1: oy + 10 },
      { name: "living", x0: ox + 7, y0: oy + 5, x1: ox + 14, y1: oy + 10 },
    ],
    doorways: [
      { x: ox + 7, y: oy + 7 },   // living ↔ kitchen
      { x: ox + 3, y: oy + 5 },   // kitchen ↔ bedroom
      { x: ox + 11, y: oy + 5 },  // living ↔ workshop (sealed until built)
      { x: ox + 11, y: oy + 10 }, // entrance (living ↔ lot)
    ],
    entry: { x: ox + 11, y: oy + 9 },
    exitDoor: { x: ox + 11, y: oy + 10 },
    sealDoor: { x: ox + 11, y: oy + 5 },
    footings: [
      { category: "bed", room: "bedroom", x: ox + 2, y: oy + 2 },
      { category: "display", room: "bedroom", x: ox + 5, y: oy + 1 },
      { category: "lighting", room: "bedroom", x: ox + 5, y: oy + 3 },
      { category: "workshop", room: "workshop", x: ox + 9, y: oy + 2 },
      { category: "forge", room: "workshop", x: ox + 12, y: oy + 1 },
      { category: "alchemy", room: "workshop", x: ox + 12, y: oy + 3 },
      { category: "kitchen", room: "kitchen", x: ox + 2, y: oy + 6 },
      { category: "storage", room: "kitchen", x: ox + 5, y: oy + 6 },
      { category: "lighting", room: "kitchen", x: ox + 2, y: oy + 8 },
      { category: "hall", room: "living", x: ox + 13, y: oy + 6 },
      { category: "lighting", room: "living", x: ox + 9, y: oy + 6 },
      { category: "display", room: "living", x: ox + 13, y: oy + 8 },
      { category: "table", room: "living", x: ox + 10, y: oy + 8 },
      { category: "seating", room: "living", x: ox + 8, y: oy + 9 },
      // Rugs are floor coverings you walk over (their footing doesn't block).
      { category: "rug", room: "living", x: ox + 11, y: oy + 7 },
      { category: "rug", room: "bedroom", x: ox + 3, y: oy + 3 },
    ],
  };
}

/** Each home: its interior origin column + its overworld lot tiles (lot tiles
 *  are legacy coords run through remap() so they sit with the shifted city). */
const HOME_LOTS_LEGACY: { plot: string; ox: number; marker: V; door: V; exit: V }[] = [
  { plot: "home_redmouth", ox: 2, marker: { x: 81, y: 64 }, door: { x: 84, y: 65 }, exit: { x: 84, y: 66 } },
  { plot: "home_drover", ox: 20, marker: { x: 74, y: 73 }, door: { x: 77, y: 74 }, exit: { x: 77, y: 75 } },
  { plot: "home_fold", ox: 38, marker: { x: 59, y: 8 }, door: { x: 62, y: 9 }, exit: { x: 62, y: 10 } },
];
export const HOMES: {
  plot: string; ox: number;
  lot: { marker: V; door: V; exit: V };
}[] = HOME_LOTS_LEGACY.map((h) => ({
  plot: h.plot, ox: h.ox,
  lot: { marker: remap(h.marker.x, h.marker.y), door: remap(h.door.x, h.door.y), exit: remap(h.exit.x, h.exit.y) },
}));
export { HOUSE_W as HOME_WIDTH };

/** Tiles that block movement (mirrors the core's walkability check). */
const BLOCKED = new Set<TileType>(["water", "mountain", "cave_wall", "deep", "wall"]);

/** A cheap, stable pseudo-noise so terrain is fixed (not random). */
function noise(x: number, y: number): number {
  const n = Math.sin(x * 157.31 + y * 113.77) * 43758.5453;
  return n - Math.floor(n);
}

// --- Region tile rules. Each takes coordinates in the region's ORIGINAL local
// space (the same numbers it always used), so the internal layout is unchanged;
// decode() maps each new-canvas tile back to those local coords. ---

function forestTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the Lodge road
  const fringe = x < 2 || x > 25;
  const inClearing = y >= 24 && y <= 27 && x >= 5 && x <= 22;
  if (inClearing) return "dirt";
  return fringe ? "grass" : "moss";
}

function spineTile(x: number, y: number): TileType {
  const sx = x - 28;
  if ((x === 39 || x === 40) && y >= 9 && y <= 27) return "water"; // Cold Stream
  if (sx <= 3 && y >= 5 && y <= 9) return "stone"; // the pass off the hills
  // Clumped peaks at a lower density form a few ridges with clear lanes between,
  // rather than scattered single blocks you have to thread around every step.
  const peakChance = sx < 6 ? 0.82 : 0.76;
  if (clump(x, y) > peakChance) return "mountain";
  return sx < 6 || y < 5 ? "stone" : "snow";
}

/** Coarse noise: each 2×2 block shares a value, so blockers form clumps (rock
 *  masses / ridges) rather than single-tile speckle that mazes up traversal. */
function clump(x: number, y: number): number {
  return noise(Math.floor(x / 2), Math.floor(y / 2));
}

function marrowTile(x: number, y: number): TileType {
  // Clumped walls at a lower density read as cavern walls with broad galleries
  // between them, instead of a salt-and-pepper maze.
  if (clump(x, y) > 0.66) return "cave_wall";
  return "cave";
}

function heartmoorTile(x: number, y: number): TileType {
  if (x === 13 || x === 14) return "path"; // the road continues south
  const n = noise(x, y);
  if (n > 0.84) return "water"; // bog pools (impassable)
  if (n < 0.12) return "grass"; // firmer tussocks
  return "bog";
}

function ashfenTile(x: number, y: number): TileType {
  if (noise(x, y) > 0.85) return "stone"; // warm outcrops
  return "ash";
}

function redrunTile(x: number, y: number): TileType {
  if (y >= 51) return "deep"; // the open Eyeless Sea to the south
  const widen = Math.floor((y - 28) / 7);
  const left = 54 - widen;
  const right = 57 + widen;
  if (x >= left && x <= right) return "water"; // the red river, widening
  return noise(x, y) > 0.72 ? "dirt" : "grass"; // banks
}

/**
 * Each wilderness region: its tile rule, the top-left of its ORIGINAL local
 * coordinate box, its size, and where that box now sits on the bigger canvas.
 * `dx/dy` (new origin − old origin) is exported so spawns.ts can shift every
 * object the same way and stay perfectly aligned with the terrain.
 */
export interface RegionPlacement {
  key: string;
  fn: (x: number, y: number) => TileType;
  ogx: number; ogy: number; // original local origin
  w: number; h: number;
  nx: number; ny: number; // new origin on the canvas
}

export const REGIONS: RegionPlacement[] = [
  { key: "spine", fn: spineTile, ogx: 28, ogy: 0, w: 20, h: 34, nx: 47, ny: 5 },
  { key: "marrow", fn: marrowTile, ogx: 48, ogy: 0, w: 16, h: 28, nx: 121, ny: 10 },
  { key: "redrun", fn: redrunTile, ogx: 48, ogy: 28, w: 16, h: 28, nx: 134, ny: 101 },
  { key: "ashfen", fn: ashfenTile, ogx: 28, ogy: 34, w: 20, h: 22, nx: 68, ny: 137 },
  { key: "heartmoor", fn: heartmoorTile, ogx: 0, ogy: 34, w: 28, h: 22, nx: 1, ny: 133 },
  { key: "greyoak", fn: forestTile, ogx: 0, ogy: 18, w: 28, h: 16, nx: 1, ny: 73 },
];

/** Per-region spawn shift (new origin − old origin). Keyed by region. */
export const REGION_OFFSET: Record<string, { dx: number; dy: number }> = Object.fromEntries(
  REGIONS.map((r) => [r.key, { dx: r.nx - r.ogx, dy: r.ny - r.ogy }]),
);

/** The arena band moved down with the taller overworld; spawns shift by this. */
export const ARENA_OFFSET = { dx: 0, dy: BAND_DY };

// --- Ironvale, the central city (hand-built, then shifted by CENTRAL_SHIFT). ---
// A walled rectangle with four gates. West half is the civic yard (bank, forge,
// stations); the east half is the market street, lined with stalls. The home
// Knuckle Hills (grove, outcrop, lake, farmstead) wrap the city outside.
const CDX = CENTRAL_SHIFT.dx, CDY = CENTRAL_SHIFT.dy;
export const CITY = { x0: 44 + CDX, y0: 38 + CDY, x1: 79 + CDX, y1: 67 + CDY };
/** Gate centres, in canvas coords — roads meet the city here. */
export const GATES = {
  north: { x: 60 + CDX, y: CITY.y0 },
  south: { x: 60 + CDX, y: CITY.y1 },
  west: { x: CITY.x0, y: 52 + CDY },
  east: { x: CITY.x1, y: 52 + CDY },
};
/** A good, central, walkable spawn tile for the player (the civic yard). */
export const CITY_SPAWN = { x: 55 + CDX, y: 52 + CDY };

/** A roofed building in Ironvale. Its footprint blocks; the renderer roofs it. */
export type RoofStyle = "slate" | "tile" | "thatch" | "tower";
export interface Building {
  x0: number; y0: number; x1: number; y1: number;
  roof: RoofStyle;
  /** Door cell (on the building's front), for the rendered doorway. */
  door?: { x: number; y: number };
}

// The city's buildings + the outlying hamlet cottages, authored in LEGACY coords
// and shifted by CENTRAL_SHIFT (so they ride with the re-centred city block).
const BUILDINGS_LEGACY: Building[] = [
  // --- North wall row ---
  { x0: 45, y0: 39, x1: 49, y1: 41, roof: "slate", door: { x: 47, y: 41 } },  // The Ashforge
  { x0: 51, y0: 39, x1: 55, y1: 41, roof: "tile", door: { x: 53, y: 41 } },   // The Varath Vault
  { x0: 62, y0: 39, x1: 66, y1: 41, roof: "tile", door: { x: 64, y: 41 } },   // Quartermaster's Store
  { x0: 68, y0: 39, x1: 72, y1: 41, roof: "slate", door: { x: 70, y: 41 } },  // The Armoury
  { x0: 75, y0: 39, x1: 78, y1: 42, roof: "tower", door: { x: 76, y: 42 } },  // The Watchtower
  // --- West wall ---
  { x0: 45, y0: 44, x1: 47, y1: 49, roof: "slate", door: { x: 47, y: 49 } },  // The Pale Record
  { x0: 45, y0: 55, x1: 47, y1: 60, roof: "thatch", door: { x: 47, y: 60 } }, // houses
  // --- East wall ---
  { x0: 76, y0: 44, x1: 78, y1: 49, roof: "thatch", door: { x: 76, y: 49 } },
  { x0: 76, y0: 55, x1: 78, y1: 60, roof: "thatch", door: { x: 76, y: 55 } },
  // --- South wall row ---
  { x0: 45, y0: 64, x1: 50, y1: 66, roof: "slate", door: { x: 47, y: 64 } },  // The Craftworks
  { x0: 52, y0: 64, x1: 57, y1: 66, roof: "tile", door: { x: 54, y: 64 } },   // The Mending House
  { x0: 62, y0: 64, x1: 66, y1: 66, roof: "thatch", door: { x: 64, y: 64 } }, // Skritt's Exchange
  { x0: 68, y0: 64, x1: 73, y1: 66, roof: "tile", door: { x: 70, y: 64 } },   // The Wayfarers' Lodge
  { x0: 75, y0: 64, x1: 78, y1: 66, roof: "thatch", door: { x: 76, y: 64 } },

  // === OUTLYING SETTLEMENTS — small hamlets in the open country near the city.
  // --- Redmouth: a fisherfolk hamlet on the Redrun's east bank ---
  { x0: 83, y0: 58, x1: 85, y1: 59, roof: "thatch", door: { x: 84, y: 59 } },  // a fisher's cottage
  { x0: 87, y0: 58, x1: 89, y1: 59, roof: "thatch", door: { x: 88, y: 59 } },  // the net-loft
  { x0: 83, y0: 61, x1: 85, y1: 62, roof: "thatch", door: { x: 84, y: 61 } },  // the smokehouse
  // --- The Drover's Rest: a waystation on the south road to the Ashfen ---
  { x0: 65, y0: 73, x1: 68, y1: 74, roof: "tile", door: { x: 66, y: 74 } },    // the longhouse inn
  { x0: 70, y0: 73, x1: 72, y1: 74, roof: "thatch", door: { x: 71, y: 74 } },  // a drover's cottage
  { x0: 65, y0: 77, x1: 67, y1: 78, roof: "thatch", door: { x: 66, y: 77 } },  // the byre
  // --- The Fold: an upland shepherds' croft in the Knuckle Hills, north ---
  { x0: 60, y0: 14, x1: 62, y1: 15, roof: "thatch", door: { x: 61, y: 15 } },  // the croft house
  { x0: 64, y0: 14, x1: 66, y1: 15, roof: "thatch", door: { x: 64, y: 15 } },  // the wool-shed
  { x0: 60, y0: 17, x1: 62, y1: 18, roof: "thatch", door: { x: 61, y: 17 } },  // the lambing shed
];
const shiftDoor = (d?: { x: number; y: number }) => (d ? { x: d.x + CDX, y: d.y + CDY } : undefined);
export const BUILDINGS: Building[] = BUILDINGS_LEGACY.map((b) => {
  const out: Building = { x0: b.x0 + CDX, y0: b.y0 + CDY, x1: b.x1 + CDX, y1: b.y1 + CDY, roof: b.roof };
  const d = shiftDoor(b.door);
  if (d) out.door = d;
  return out;
});

/** Roof style at a tile (so the renderer knows which walls are buildings). */
const roofCells = new Map<string, RoofStyle>();
const doorCells = new Set<string>();
for (const b of BUILDINGS) {
  for (let y = b.y0; y <= b.y1; y++) for (let x = b.x0; x <= b.x1; x++) roofCells.set(`${x},${y}`, b.roof);
  if (b.door) doorCells.add(`${b.door.x},${b.door.y}`);
}
export function cityRoof(x: number, y: number): RoofStyle | undefined { return roofCells.get(`${x},${y}`); }
export function cityDoor(x: number, y: number): boolean { return doorCells.has(`${x},${y}`); }

function decode(): WorldMap {
  const tiles: TileType[] = new Array(WIDTH * HEIGHT).fill("grass");
  const set = (x: number, y: number, t: TileType) => {
    if (x >= 0 && y >= 0 && x < WIDTH && y < HEIGHT) tiles[y * WIDTH + x] = t;
  };
  const carve = (x0: number, y0: number, x1: number, y1: number, t: TileType) => {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) set(x, y, t);
  };
  // Central-complex carves: authored in LEGACY coords, shifted by CENTRAL_SHIFT
  // so they ride with the re-centred city (mirrors remap() for spawns).
  const cc = (x0: number, y0: number, x1: number, y1: number, t: TileType) =>
    carve(x0 + CDX, y0 + CDY, x1 + CDX, y1 + CDY, t);

  // 1) The arena band starts as solid wall; rooms are carved later.
  for (let y = OVERWORLD_HEIGHT; y < HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) set(x, y, "wall");
  }

  // 2) Paint each wilderness region at its new home (same internal layout).
  for (const r of REGIONS) {
    for (let cy = r.ny; cy < r.ny + r.h; cy++) {
      for (let cx = r.nx; cx < r.nx + r.w; cx++) {
        const ox = cx - r.nx + r.ogx;
        const oy = cy - r.ny + r.ogy;
        set(cx, cy, r.fn(ox, oy));
      }
    }
  }

  // 2b) Repair any floor pocket a clump walled off, so every cavern/ledge stays
  //     reachable (it only opens blockers, never strands a spawn).
  const inRect = (x: number, y: number, x0: number, y0: number, x1: number, y1: number): boolean =>
    x >= x0 && x <= x1 && y >= y0 && y <= y1;
  const repairConnectivity = (
    x0: number, y0: number, x1: number, y1: number, floorAt: (x: number, y: number) => TileType,
  ): void => {
    const walkableHere = (x: number, y: number): boolean =>
      inRect(x, y, x0, y0, x1, y1) && !BLOCKED.has(tiles[y * WIDTH + x]!);
    const seen = new Set<number>();
    const pockets: [number, number][][] = [];
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
      const idx = y * WIDTH + x;
      if (!walkableHere(x, y) || seen.has(idx)) continue;
      const cells: [number, number][] = []; const q: [number, number][] = [[x, y]]; seen.add(idx);
      while (q.length) {
        const [cx, cy] = q.shift()!; cells.push([cx, cy]);
        for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]] as const) {
          const nx = cx + dx, ny = cy + dy, ni = ny * WIDTH + nx;
          if (walkableHere(nx, ny) && !seen.has(ni)) { seen.add(ni); q.push([nx, ny]); }
        }
      }
      pockets.push(cells);
    }
    if (pockets.length <= 1) return;
    pockets.sort((a, b) => b.length - a.length);
    const centre = (c: [number, number][]): [number, number] =>
      [Math.round(c.reduce((s, p) => s + p[0], 0) / c.length), Math.round(c.reduce((s, p) => s + p[1], 0) / c.length)];
    const [mx, my] = centre(pockets[0]!);
    for (let i = 1; i < pockets.length; i++) {
      let [cx, cy] = centre(pockets[i]!);
      let guard = 0;
      while ((cx !== mx || cy !== my) && guard++ < 200) {
        if (cx !== mx) cx += Math.sign(mx - cx);
        else if (cy !== my) cy += Math.sign(my - cy);
        if (inRect(cx, cy, x0, y0, x1, y1) && BLOCKED.has(tiles[cy * WIDTH + cx]!)) set(cx, cy, floorAt(cx, cy));
      }
    }
  };

  const marrow = REGIONS.find((r) => r.key === "marrow")!;
  const spine = REGIONS.find((r) => r.key === "spine")!;
  repairConnectivity(marrow.nx, marrow.ny, marrow.nx + marrow.w - 1, marrow.ny + marrow.h - 1, () => "cave");
  repairConnectivity(spine.nx, spine.ny, spine.nx + spine.w - 1, spine.ny + spine.h - 1, (x, y) => {
    const sx = (x - spine.nx + spine.ogx) - 28;
    return sx < 6 || (y - spine.ny + spine.ogy) < 5 ? "stone" : "snow";
  });

  // 3) The home Knuckle Hills wrap the city: a dirt grove + rock outcrop to the
  //    north, a lake to the south-west, open hill grass all around.
  cc(44 - 6, 38 - 14, 79 + 6, 38 - 1, "grass"); // hill apron north
  cc(50, 24, 70, 33, "dirt");   // the dirt grove (Forestry)
  cc(82, 28, 92, 38, "stone");  // the knucklestone outcrop (Mining), NE
  cc(34, 70, 43, 82, "water");  // the lake on the city's south-west flank
  cc(80, 38, 86, 67, "grass");  // east apron to the river road

  // 4) Build Ironvale at the centre (CITY/GATES are already shifted).
  //    Plaza floor: stone in the civic (west) half, dirt in the market (east).
  carve(CITY.x0, CITY.y0, CITY.x1, CITY.y1, "stone");
  cc(63, 39, 79 - 1, 67 - 1, "dirt"); // market ground (east)
  //    Wall ring.
  for (let x = CITY.x0; x <= CITY.x1; x++) { set(x, CITY.y0, "wall"); set(x, CITY.y1, "wall"); }
  for (let y = CITY.y0; y <= CITY.y1; y++) { set(CITY.x0, y, "wall"); set(CITY.x1, y, "wall"); }
  //    Main streets (a cross joining the four gates).
  cc(59, 38, 61, 67, "path"); // N–S high street
  cc(44, 51, 79, 53, "path"); // E–W high street
  //    Four gates (open the wall ring where the roads meet it).
  carve(GATES.north.x - 1, CITY.y0, GATES.north.x + 1, CITY.y0, "path");
  carve(GATES.south.x - 1, CITY.y1, GATES.south.x + 1, CITY.y1, "path");
  carve(CITY.x0, GATES.west.y - 1, CITY.x0, GATES.west.y + 1, "path");
  carve(CITY.x1, GATES.east.y - 1, CITY.x1, GATES.east.y + 1, "path");
  //    Outlying hamlets: a packed-dirt yard, then a vacant homestead lot beside.
  cc(81, 57, 90, 63, "dirt");  // Redmouth, on the Redrun's east bank
  cc(63, 72, 73, 79, "dirt");  // The Drover's Rest, on the south road
  cc(58, 13, 67, 19, "dirt");  // The Fold, in the upland Knuckle Hills
  cc(81, 64, 86, 67, "dirt");  // Redmouth homestead lot
  cc(74, 73, 79, 76, "dirt");  // Drover's Rest homestead lot
  cc(59, 8, 64, 11, "dirt");   // The Fold homestead lot
  //    The buildings: each footprint becomes blocking masonry (roofed by the renderer).
  for (const b of BUILDINGS) carve(b.x0, b.y0, b.x1, b.y1, "wall");
  //    A flagged town square around the crossroads, for the fountain + crowds.
  cc(58, 50, 62, 54, "stone");

  // 4b) Countryside features around the city (the bible's named Knuckle Hills
  //     landmarks) — shifted with the central complex.
  cc(8, 6, 14, 12, "dirt");     // Rook's Watch — a high firepit knoll
  cc(18, 8, 26, 16, "stone");   // The Knuckle — the bald stone fist
  cc(14, 18, 22, 24, "dirt");   // an ashwood grove
  cc(28, 29, 33, 34, "water");  // a hill tarn (a head-stream pool)
  cc(5, 30, 11, 36, "stone");   // The Coldvein Scar — a played-out cutting
  cc(2, 64, 8, 70, "dirt");     // The Charburner's Clearing

  // 4d) NEW POIs filling the wide open country the bigger map opened up. Each is
  //     a patch of real ground a player can find between the city and a region.
  carve(36, 40, 44, 47, "stone");    // The Wayfarers' Crossroads ruin (NW, city→greyoak/spine)
  carve(112, 46, 122, 56, "stone");  // The Old Quarry (NE, city→marrow)
  carve(110, 96, 122, 106, "grass"); // The East Commons — drovers' meadow (E, city→redrun)
  carve(96, 112, 108, 124, "dirt");  // The Gallowsfield camp (SE, city→ashfen)
  carve(36, 104, 48, 116, "bog");    // The Sunken Mile (SW, city→heartmoor)
  carve(30, 80, 42, 90, "dirt");     // The Wood-Moor Verge (W, city→greyoak)

  // 4c) Heath: give the remaining open grass a rolling, mixed texture instead of
  //     a flat green sheet (all walkable — grass / dirt / moss hill country).
  for (let y = 0; y < OVERWORLD_HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) {
      if (tiles[y * WIDTH + x] !== "grass") continue;
      const n = noise(x, y);
      if (n > 0.86) set(x, y, "moss");
      else if (n > 0.66) set(x, y, "dirt");
      // else: stays grass
    }
  }

  // 5) Long roads from the gates out to each far region (3 wide, walkable). The
  //    regions sit far from the centre now, so these are real journeys.
  const greyoak = REGIONS.find((r) => r.key === "greyoak")!;
  const ashfen = REGIONS.find((r) => r.key === "ashfen")!;
  const heartmoor = REGIONS.find((r) => r.key === "heartmoor")!;
  const redrun = REGIONS.find((r) => r.key === "redrun")!;
  const road = (x0: number, y0: number, x1: number, y1: number) => carve(x0, y0, x1, y1, "path");
  const stoneRd = (x0: number, y0: number, x1: number, y1: number) => carve(x0, y0, x1, y1, "stone");
  // North gate → the Spine pass (its walkable stone pass is at its west edge).
  road(GATES.north.x - 1, spine.ny + 14, GATES.north.x + 1, CITY.y0 - 1); // up to the pass
  road(spine.nx + 2, spine.ny + 13, GATES.north.x + 1, spine.ny + 15);    // west along to the pass foot
  stoneRd(spine.nx, spine.ny + 5, spine.nx + 3, spine.ny + 16);           // into the Spine pass
  // West gate → Greyoak Wood (its Lodge road is at local x13–14 → canvas nx+13).
  road(greyoak.nx + 14, GATES.west.y - 1, CITY.x0 - 1, GATES.west.y + 1);
  // South gate → Ashfen Flats via a long moor road.
  road(GATES.south.x - 1, CITY.y1 + 1, GATES.south.x + 1, ashfen.ny);
  road(ashfen.nx + 8, ashfen.ny - 2, GATES.south.x + 1, ashfen.ny);
  // South-west spur → Heartmoor (its road is at local x13–14 → canvas nx+13).
  road(heartmoor.nx + 14, GATES.south.y, heartmoor.nx + 16, heartmoor.ny); // down the moor
  road(heartmoor.nx + 14, GATES.south.y, GATES.south.x, GATES.south.y + 2); // link to the south road
  // East gate → the Redrun & the river road.
  road(CITY.x1 + 1, GATES.east.y - 1, redrun.nx, GATES.east.y + 1);       // east across the commons
  road(redrun.nx - 1, GATES.east.y, redrun.nx + 1, redrun.ny);            // down to the riverbank
  // North-east spur → the Marrow Deeps cave mouth (an L: up the outcrop, then
  //    across to the cave). carve() only fills left→right / top→down, so keep
  //    each leg's corners ordered.
  stoneRd(CITY.x1, marrow.ny + 15, CITY.x1 + 2, GATES.east.y);            // up from the east road
  stoneRd(CITY.x1, marrow.ny + 15, marrow.nx, marrow.ny + 16);           // across to the outcrop
  carve(marrow.nx, marrow.ny + 12, marrow.nx + 3, marrow.ny + 16, "cave"); // into the cave mouth

  // 5b) Short lanes joining the outlying hamlets to the road network.
  cc(84, 54, 85, 57, "path");   // Redmouth lane up to the east road
  cc(61, 75, 64, 76, "path");   // The Drover's Rest, off the south road
  cc(58, 19, 60, 24, "path");   // The Fold, down to the grove

  // 6) Carve the four sealed boss arenas in the band below the overworld.
  for (const a of ARENAS) {
    for (let y = ARENA_TOP; y < ARENA_TOP + ARENA_H; y++) {
      for (let x = a.x; x < a.x + ARENA_W; x++) {
        const edge = x === a.x || x === a.x + ARENA_W - 1 || y === ARENA_TOP || y === ARENA_TOP + ARENA_H - 1;
        set(x, y, edge ? "wall" : a.floor);
      }
    }
  }

  // 7) Carve each player-home interior in the band below the arenas.
  for (const h of HOMES) {
    const plan = homeLayout(h.ox);
    for (const rm of plan.rooms) {
      for (let y = rm.y0; y <= rm.y1; y++) {
        for (let x = rm.x0; x <= rm.x1; x++) {
          const edge = x === rm.x0 || x === rm.x1 || y === rm.y0 || y === rm.y1;
          set(x, y, edge ? "wall" : "plank");
        }
      }
    }
    for (const d of plan.doorways) set(d.x, d.y, "plank"); // openings (incl. the sealed wing doorway)
  }

  return { name: "Varath", width: WIDTH, height: HEIGHT, tiles };
}

export const map: WorldMap = decode();

/** A bounded "instance" rectangle (inclusive tile bounds) for view isolation. */
export interface InstanceRect { x0: number; y0: number; x1: number; y1: number }

/**
 * The instance the given tile belongs to — a player home or a boss arena — or
 * null for the open overworld. The renderer uses this to show ONLY the current
 * instance (a sealed room), so you never see the neighbouring rooms or the
 * arena band around it.
 */
export function instanceRectAt(x: number, y: number): InstanceRect | null {
  if (y < OVERWORLD_HEIGHT) return null; // the overworld is never masked
  for (const h of HOMES) {
    if (x >= h.ox && x <= h.ox + HOUSE_W - 1 && y >= INTERIOR_TOP && y <= INTERIOR_TOP + 10) {
      return { x0: h.ox, y0: INTERIOR_TOP, x1: h.ox + HOUSE_W - 1, y1: INTERIOR_TOP + 10 };
    }
  }
  for (const a of ARENAS) {
    if (x >= a.x && x <= a.x + ARENA_W - 1 && y >= ARENA_TOP && y <= ARENA_TOP + ARENA_H - 1) {
      return { x0: a.x, y0: ARENA_TOP, x1: a.x + ARENA_W - 1, y1: ARENA_TOP + ARENA_H - 1 };
    }
  }
  return null;
}

/** Convenience: read the tile type at a coordinate (grass if out of bounds). */
export function tileAt(m: WorldMap, x: number, y: number): TileType {
  if (x < 0 || y < 0 || x >= m.width || y >= m.height) return "grass";
  return m.tiles[y * m.width + x]!;
}
